version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:10.17.0
    working_directory: ~/repo

jobs:
  build:
    executor: node
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install
      - run: npx oz compile

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/
          paths:
            - repo
            - .ssh

  test:
    executor: node
    steps:
      - attach_workspace:
          at: ~/
      - run: npm test

  publish:
    executor: node
    steps:
      - attach_workspace:
          at: ~/
      - run: npx semantic-release

workflows:
  version: 2
  all:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          context: ohmydai
          requires:
            - test
